insert into WEBS.ENTITLED_PRODUCT_FEATURE (
    ENTITLED_PRODUCT_FEATURE_ID,
    ENTITLED_PRODUCT_ID,
    FEATURE_OFFER_ID,
    FEATURE_CODE,
    ENTITLED_FEATURE_STATE,
    SERVICE_STATE_ID,
    ENTITLESTATE_CHANGE_REASON_ID,
    CREATE_DATE,
    UPDATE_DATE
)
values (
    24894,
    100120,
    0,
    'HOST_5_USER',
    'ACTIVE',
    103,
    null,
    '2019-08-05',
    '2019-09-05'
);
